### ISSUE TITLE
Notifications - Double notifications for some events

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#417] opened 2021-04-26 14:23 UTC
Reported by Arava at common-qa-bugs 
![IMG_7973](https://user-images.githubusercontent.com/30501647/116098750-4f806400-a679-11eb-86bb-ce548f44ad0a.JPG)

Seems like that the post was created twice in the database
<img width="317" alt="Screen Shot 2021-04-26 at 10 23 29" src="https://user-images.githubusercontent.com/30501647/116098930-75a60400-a679-11eb-96f6-d25b2324eb50.png">

**Comment by yanivi71** [comment] 2021-05-10 19:04
Tested on Staging iOS version 1.9.7 (6591)
Tested on Staging Android version 1.9.7 (6591-240)

Cannot reproduce.
moving to verify

**Comment by yanivi71** [comment] 2021-05-30 08:40
testen on production
Cannot reproduce.

**Closed as completed by yanivi71** 2021-05-30 08:40 UTC
Labels: bug
