### ISSUE TITLE
Billing  - Add expiration date and cardholder name

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#1289] opened 2022-04-20 09:27 UTC
Tested on iOS v 1.11.2 (15-316)
Tested on Android v 1.0 (401)
Design - https://zpl.io/aBQWZzK

Make some changes on the Billing page, with the tab with Saved payment method:
1. Add the cardholder First and Last name
2. Add the expiration date of the card

![08 05 02 billing - saved payment method - Common M](https://user-images.githubusercontent.com/68247034/164197101-1d822fd9-d854-4d05-95be-2d9e4aacdb6a.png)

**Comment by kazaryan-t** [comment] 2022-04-22 17:37
The expiration date of the card is displayed as 00/00.
![photo_2022-04-22_20-38-14](https://user-images.githubusercontent.com/68247034/164765948-03474759-5dcb-4dfb-b983-b5a7d2479f3a.jpg)

**Comment by watchtower314** [comment] 2022-04-24 09:39
@yanivi71  @kazaryan-t This is not a bug -> for cards that were created before we used PayMe, we don't have expiration date saved in the database, this will not be a problem once users replace their Circle payment method to PayMe

**Comment by yanivi71** [comment] 2022-04-24 11:01
Closing this issue according to the comment above

**Closed as completed by yanivi71** 2022-04-24 11:01 UTC
Labels: bug
