### ISSUE TITLE
Moderation improvements

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#169] opened 2021-03-04 07:55 UTC
For after the release of the current moderation
- [x] make moderator note mandatory
- [x] stop countdown for hidden proposals

**Comment by yanivi71** [comment] 2021-05-10 18:35
Tested on Staging iOS version 1.9.7 (6591)
Tested on Staging Android version 1.9.7 (6591-240)
@watchtower314 
1. When Membership request is hidden the countdown continues
2. When funding proposal is hidden the countdown continues
3. report button is not active even if i insert note. it becomes active if I click on other reason options from the report page

**Comment by watchtower314** [comment] 2021-05-20 01:18
This ticket has two prs that fix it:

backend pr (fixes the countdown): https://github.com/daostack/common-monorepo/pull/495

frontend pr: (fixes the enabling/disabling of report button) : https://github.com/daostack/common/pull/1087
demo:

https://user-images.githubusercontent.com/30501647/118904373-6e91af00-b922-11eb-890f-799d5543933b.mov

**Comment by yanivi71** [comment] 2021-05-23 14:20
Tested on Staging iOS version 1.9.7 (6591-283)
Tested on Staging Android version 1.9.7 (6591-244)
Not fixed

https://user-images.githubusercontent.com/69141571/119264035-36bc8d00-bbea-11eb-9288-cd62b48a8f71.mp4


Steps to reproduce:
1. Create a new membership  request to join a common
2. As a moderator Hide the request - Results Countdown stops
3. Wait for 5 hours
4. As a moderator show the request - Results Countdown starts from the latest time

Actual results:
The request is rejected but the countdown continues - see attached video.
it seems that the countdown value ignored the stop time
**Note - Please verify that the same fix  funding request**

Expected results:
the request should not be rejected until countdown is finished

**Comment by alexander2001i** [comment] 2021-06-07 05:06
FYI: The backend for the issue is merged, but not deployed

**Closed as completed** 2021-11-09 17:08 UTC
