### ISSUE TITLE
Store common member rules acceptance info

### ISSUE THREAD

**Issue by andreymikhadyuk** [daostack/common-backend#1648] opened 2023-02-19 11:17 UTC
We need to save the info where the user has accepted the common rules: in the regular or supporters flow.

**Comment by andreymikhadyuk** [comment] 2023-02-19 11:20
@elatif2020 What about the case, when user has joined the project using circle joining. What should we store for rules in such case? And do we actually need to store this info for projects?

**Comment by elatif2020** [comment] 2023-02-19 15:55
> @elatif2020 What about the case, when user has joined the project using circle joining. What should we store for rules in such case? And do we actually need to store this info for projects?

we should mark the rules accepted flag to be true

**Comment by ariel-dao** [comment] 2023-02-21 14:05
@elatif2020 what about existing common members? should they be marked as seen rules?

**Comment by ariel-dao** [comment] 2023-02-21 14:40
@andreymikhadyuk Added EP POST `commons/accept-rules`, body: { commonId: string }

**Comment by elatif2020** [comment] 2023-02-21 15:55
> @elatif2020 what about existing common members? should they be marked as seen rules?

for users who joined before this change? yes

**Comment by andreymikhadyuk** [comment] 2023-02-22 05:29
@ariel-dao I see that you've added `rulesAccepted: boolean` field, but what about the place where user has accepted the rules? If I am correct, we should store whether rules were accepted in the `regular` flow, `supporters` flow or a circle assignment, when we should just have `true` to mark that rules are accepted. @elatif2020 correct me please if I am wrong.

**Comment by elatif2020** [comment] 2023-02-22 15:54
> @ariel-dao I see that you've added `rulesAccepted: boolean` field, but what about the place where user has accepted the rules? If I am correct, we should store whether rules were accepted in the `regular` flow, `supporters` flow or a circle assignment, when we should just have `true` to mark that rules are accepted. @elatif2020 correct me please if I am wrong.

Actually I am not sure. Why do we need to deferentiate btw these cases?

**Comment by andreymikhadyuk** [comment] 2023-02-23 02:55
@elatif2020 As I remember you told this)) If it is unnecessary, then `boolean` is fine for us.

**Comment by andreymikhadyuk** [comment] 2023-02-23 07:11
@ariel-dao @elatif2020 I think after successful common join the `rulesAccepted` should be `true`.

**Comment by andreymikhadyuk** [comment] 2023-02-23 07:55
@ariel-dao @elatif2020 Am I correct that the only place where we need to call rules acceptance explicitly is supporters flow? Other places will mark rules as accepted automatically?

**Comment by ariel-dao** [comment] 2023-02-23 09:50
@andreymikhadyuk correct

**Comment by elatif2020** [comment] 2023-03-06 12:22
@andreymikhadyuk @ariel-dao  should we move this ticket to done\staging ?

**Comment by andreymikhadyuk** [comment] 2023-03-06 12:26
@ariel-dao @elatif2020 `rulesAccepted` field is still `false` after joining a common.

**Comment by ariel-dao** [comment] 2023-03-07 10:22
@andreymikhadyuk How did you join the common? need steps to reproduce

**Comment by ariel-dao** [comment] 2023-03-11 17:33
@andreymikhadyuk @elatif2020 is this still relevant after dumping db?

**Comment by elatif2020** [comment] 2023-03-11 21:05
@ariel-dao 
As I understand the issue is that we somehow need to make sure that the `rulesAccepted` flag is `true` also if a user joins the common through the regular join flow (not through the supporters flow).

**Comment by andreymikhadyuk** [comment] 2023-03-13 02:57
@ariel-dao @elatif2020 I've just joined `ad5a7455-e13e-4a36-aa93-02b38e57ec89` on dev and `rulesAccepted` is `true`.

**Comment by andreymikhadyuk** [comment] 2023-03-13 02:58
@ariel-dao If this is deployed to prod, then please move the ticket to `Deployed`.

**Closed as completed** 2023-03-13 02:58 UTC
Labels: Priority - A
