### ISSUE TITLE
Stream counter isn't reseted on (new) message(s) deletion

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2156] opened 2023-10-05 14:03 UTC
User 1 is following Home in Air space
User 2 write a message there and delete it

-> User 1 see unread counter for this stream, and also the counter isn't cleared when opening this discussion (but it does when marking the item as read)

**Comment by ariel-dao** [comment] 2023-10-07 13:01
https://github.com/daostack/common-backend/commit/21b8b763911741e362d2808f45b76c7dd29e1e08

**Comment by elatif2020** [comment] 2023-10-08 07:07
Tested it again on dev, it's not fixed @arieller

**Comment by arieller** [comment] 2023-10-08 07:20
@elatif2020 its in review, not deployed yet

**Comment by elatif2020** [comment] 2023-10-08 07:36
> @elatif2020 its in review, not deployed yet

Okay, in this case it could be useful to use the status "Code Review" instead of closing the ticket (and close it once it is on dev).  @ariel-dao

**Comment by arieller** [comment] 2023-10-08 08:12
Sorry ill correct, it's already merged but not deployed. @elatif2020

**Comment by ariel-dao** [comment] 2023-10-08 15:18
Deployed to dev, please test in 5 minutes if it's closed close the task, if not include steps to reproduce
@elatif2020 @NoamQA

**Comment by elatif2020** [comment] 2023-10-09 10:01
@ariel-dao 
I rechecked this now, still there is an issue with the new messages counter (Notice that the last message preview is being corrected but the counter isn't). The steps to reproduce are (elaboration of the steps above):

Opening the app on two browsers with two different users.
User 1 is following (for example) "Members Discussion 1" in [Autumn DEV](https://web-dev.common.io/commons/4c87126a-d764-42c5-90dc-723431fa5a46) and making another item active. 
User 2 write a message in this discussion 
-> User 1 see unread counter for this discussion (but doesn't click on it) (this is correct behavior)
User 2 delete his message
-> User 1 still see unread counter for this discussion (this is incorrect) also after refresh
-> also the counter isn't cleared when opening this discussion (but it does when marking the item as read)

**Comment by elatif2020** [comment] 2023-10-09 10:04
@ariel-dao 
Also, for the Home stream I see another strange behavior, where the counter sometimes directly disappear (without opening this discussion, and without deleting the message)

**Comment by ariel-dao** [comment] 2023-10-13 13:07
@andreymikhadyuk From what I see the counter of the messages which is on the common member entity is being changed correctly, I'm using only backend for the testing, where is the data on FE is fetched from?

**Comment by andreymikhadyuk** [comment] 2023-10-16 08:45
> @andreymikhadyuk From what I see the counter of the messages which is on the common member entity is being changed correctly, I'm using only backend for the testing, where is the data on FE is fetched from?

`project` feed items:
- for unread messages we use `unreadCountByProjectStream`
- for unread streams amount we use `streamsUnreadCountByProjectStream`

**Comment by ariel-dao** [comment] 2023-10-16 21:39
makes sense I was testing `streamsUnreadCountByProjectStream`, will fix `unreadCountByProjectStream`

**Comment by ariel-dao** [comment] 2023-10-17 19:18
@andreymikhadyuk @elatif2020 @danielr18 
I've tried to figure out what's happening with the count, one thing that wasn't mentioned is that the count issue is (is it?) related to project streams in a parent common.
I've created 2 users and tested discussion message creation/deletion in a common and in a project while watching both parent and the project member entities and the under `unreadCountByProjectStream` and `streamsUnreadCountByProjectStream` are being set correctly on creation and deletion. 

Either I'm missing something unknown here like data that is being read else where, or the issue is some where else. 
From what Latif described it seems that the issue is with live updates, I cannot reproduce it. Any ideas?

**Comment by elatif2020** [comment] 2023-10-17 19:38
@arieller 
I guess we had some confusion here. The issue I described is with a feed item like a discussion not a subspace. If I understand correctly @andreymikhadyuk you were answering regarding subspace-item, correct?

**Comment by ariel-dao** [comment] 2023-10-17 19:55
Either way, I couldn't reproduce with on a discussion whether it was in a common or a subcommon

**Comment by elatif2020** [comment] 2023-10-17 20:28
@ariel-dao 
I made this recording to demonstrate how to reproduce, I hope it could help
https://github.com/daostack/common-backend/assets/72435714/0b56dc4a-4d62-496f-85a0-7df3c7fd95f2

**Comment by ariel-dao** [comment] 2023-10-17 20:58
@elatif2020 Can't reproduce.

https://github.com/daostack/common-backend/assets/89919079/3de252a7-c012-4c3c-a874-78e006f3842f

**Comment by elatif2020** [comment] 2023-10-17 21:45
@ariel-dao 
1 - Maybe it only happens if doing the action from the inbox 🤔 
2 - I see in the db, nonzero corresponding counters in daos>members>unreadCountByStream (for the relevant feedItemId) and also in dao>members>commonFeedObjectUserUnique>count (for relevant  feedItemId & user)

**Comment by arieller** [comment] 2023-10-17 22:23
Still can't reproduce...

**Comment by elatif2020** [comment] 2023-10-18 07:08
> @ariel-dao 1 - Maybe it only happens if doing the action from the inbox 🤔 2 - I see in the db, nonzero corresponding counters in daos>members>unreadCountByStream (for the relevant feedItemId) and also in dao>members>commonFeedObjectUserUnique>count (for relevant feedItemId & user)

🤔 
@MeyerPV Can you please check whether there is a difference in the FE between writing & deleting a message in the Inbox and the Feed (in terms of something related to marking the lastActivity, the indexes or anything else)?

**Comment by MeyerPV** [comment] 2023-10-18 13:34
> > @ariel-dao 1 - Maybe it only happens if doing the action from the inbox 🤔 2 - I see in the db, nonzero corresponding counters in daos>members>unreadCountByStream (for the relevant feedItemId) and also in dao>members>commonFeedObjectUserUnique>count (for relevant feedItemId & user)
> 
> 🤔 @MeyerPV Can you please check whether there is a difference in the FE between writing & deleting a message in the Inbox and the Feed (in terms of something related to marking the lastActivity, the indexes or anything else)?

It have the same functionality. We change counter in Chat and Chat is the same for inbox and Feed
Maybe @budnik9 know this better

**Comment by ariel-dao** [comment] 2023-10-18 18:04
@budnik9 Can you help please?
btw any one else managed to reproduce it and point out where it's failing?

**Comment by elatif2020** [comment] 2023-10-18 22:29
> @budnik9 Can you help please? btw any one else managed to reproduce it and point out where it's failing?

now it doesn't reproduce to me
Maybe some recent change solved it? 🤷‍♂

**Comment by budnik9** [comment] 2023-10-19 09:40
@elatif2020 @ariel-dao 

1. The issue is still reproducible for me on dev env.
2. There is no changes between inbox and feed pages. We use shared components for both pages.
3. If you want to test and fix the issue from the video that Latif attached, you need to check `CommonFeedObjectUserUnique` collection (`count` attribute).

**Comment by ariel-dao** [comment] 2023-10-20 09:17
How did you reproduce it?

**Comment by budnik9** [comment] 2023-10-20 10:06
@ariel-dao
Inbox page:
I reproduced it with the same way like in the video Latif attached https://github.com/daostack/common-backend/issues/2156#issuecomment-1767120171 . But with one difference: I wrote two messages (for example '123' and '321') and after that I deleted thee first written message ('123'). The counter was not updated

Feed page (My spaces):
Opening the app on `My spaces` page on two browsers with two different users.
User 1 is following (for example) "Test Discussion" and making another feed item active.
User 2 opens the same common/space and the same discussion and writes a message in this discussion
-> User 1 sees unread counter for this discussion (but doesn't click on it) (this is correct behavior)
User 2 deletes his message
-> User 1 still sees unread counter for this discussion (this is incorrect) also after refresh
-> also the counter isn't cleared when opening this discussion (but it does when marking the item as read)

**Comment by ariel-dao** [comment] 2023-10-21 11:44
https://github.com/daostack/common-backend/assets/89919079/e57c6d86-a010-442a-9bf5-03257767e37c

@budnik9 @elatif2020 Can't reproduce it in that way either...

**Comment by budnik9** [comment] 2023-10-23 10:05
@ariel-dao Hmm, that's strange.
 For me it's still reproducible.
 @elatif2020 @NoamQA Could you check it, too?

**Comment by NoamQA** [comment] 2023-10-23 13:26
@elatif2020 @budnik9 @ariel-dao 
yes it also reproduce for me

i think the reason is that the counter behave different for home , discussion and proposal
i tried for home channel and reproduced it (see picture below) 

ariel did on proposal and didnt reproduced - can you try doing the same in home channel of a common or space?

i cant check on discussion and proposal becose there is a [bug ](https://github.com/daostack/common-web/issues/2230)there that i opened now

![image](https://github.com/daostack/common-backend/assets/129174316/ca97ef9d-6a7f-4918-9122-7b7109048001)

**Comment by NoamQA** [comment] 2023-10-25 09:17
@elatif2020 @budnik9 @ariel-dao
i found another important related thing:
if you write a message with user A
and **immediately** delete it-
the counter for user B is increased by 1
and doesnt reduce (in the channel and inbox counter)
and doesnt disappear when opening the channel

**Comment by NoamQA** [comment] 2023-10-25 11:15
@danielr18

**Comment by NoamQA** [comment] 2023-10-26 07:00
@elatif2020 @budnik9 @danielr18 
now stream counter doesnt reset at all when i open a channel with new items
both in dev and web stage
![image](https://github.com/daostack/common-backend/assets/129174316/cc0fc5a3-8dc0-42fe-bbce-6fa169fdcc95)

**Closed as completed** 2023-10-26 10:09 UTC
Labels: bug, Priority - A, V [production]
