### ISSUE TITLE
Add floating "Join the effort" button on Discussion page

### ISSUE THREAD

**Issue by kazaryan-t** [daostack/common-backend#580] opened 2021-06-07 13:04 UTC
Add floating Join the effort button on Discussion page when the first button hides.

Steps to reproduce:
1. Open any common with discussions
2. Scroll down the page

**Actual:**
![https___s3-us-west-2 amazonaws com_secure notion-s](https://user-images.githubusercontent.com/68247034/121021123-b7ae8380-c7a9-11eb-939d-8cce19aaa5ed.png)

**Design:**
![02 03 03 - discussion - floater - Common Web - Zep](https://user-images.githubusercontent.com/68247034/121021063-a796a400-c7a9-11eb-8b76-944dd7774281.png)

**Comment by roienatan** [comment] 2021-06-07 14:32
See @Taikaish's comment here https://github.com/daostack/common-monorepo/issues/446 for the functionality.

**Comment by Taikaish** [comment] 2021-06-22 16:48
Fix required:

On iphone, the button needs to be placed higher.
The reason is that the lower part triggers a different iPhone functionality that makes the button not clickable.

![image](https://user-images.githubusercontent.com/5177733/122967011-add47500-d392-11eb-98f7-78ac28202501.png)

**Comment by kazaryan-t** [comment] 2021-06-24 11:07
1. The button shouldn't go through the footer and links on the footer and it shouldn't climb on the common name. The sticky button should appear when the top button disappears.

2. At the bottom the Join the effort button should stay above the footer, once the sticky "Join the effort" button gets to this position, it should remain there, so it won't get over the footer.

3. Also on the iphone a white gap appears when scrolling the page till the end, after the footer.

On the screenshot, you can see two extreme positions for the button, on the top, and at the bottom.

![02 02 01 - common page - Common Web - Zeplin - Goo](https://user-images.githubusercontent.com/68247034/123251865-56e6b100-d4f4-11eb-9d41-175a2b9d9e3a.png)

Actual:

https://user-images.githubusercontent.com/68247034/123252465-fd32b680-d4f4-11eb-9d27-f640fa493aa4.MP4

**Comment by razoorka** [comment] 2021-06-24 16:16
1. Will be fixed.
2. Was not able to reproduce it on my iPhone.
3. This gap is IOs feature, it will be reproduced on each site, so unfortunately we will not be able to overcome this.

**Comment by gingervik** [comment] 2021-06-24 16:26
3. Checked for several websites
Even for google and Uber 
The same behavior
![telegram-cloud-photo-size-2-5380066207987774281-y](https://user-images.githubusercontent.com/28015224/123299685-7694ce00-d522-11eb-9945-99a6ec1e9d66.jpg)
![telegram-cloud-photo-size-2-5380066207987774282-y](https://user-images.githubusercontent.com/28015224/123299706-7e547280-d522-11eb-990c-4c9080031492.jpg)

@kazaryan-t please follow the design

**Comment by kazaryan-t** [comment] 2021-06-28 07:49
1. The sticky button should appear when scrolling down the screen and the top button disappears. 
**The sticky button shouldn't appear above the top button.**
Design with extreme positions for the button, on the top, and at the bottom - https://zpl.io/ann6Y5v.

https://user-images.githubusercontent.com/68247034/123598246-f5c52300-d7fc-11eb-8965-0b5f5b79ead5.mp4

**Comment by kazaryan-t** [comment] 2021-07-02 08:58
Fix the sticky button at the bottom. It first disappears and then appears.

https://user-images.githubusercontent.com/68247034/124249518-a2b8dc00-db2c-11eb-93ab-3ae806b37066.mp4

**Closed as completed** 2021-11-09 17:25 UTC
