### ISSUE TITLE
issues with preview and updates number in  channels

### ISSUE THREAD

**Issue by NoamQA** [daostack/common-backend#2152] opened 2023-09-19 07:28 UTC
there are issues with updates in channels:

- [x] when i update home channel with another user - the time of the update doesnt change
- [x] also the preview of the update doesnt change (only number of updates works)
- [x] in proposal and discussions the number of changes and preview doesnt work (only the time of change works)

![Image](https://user-images.githubusercontent.com/129174316/268874479-7ed33b36-87a8-429c-a393-47266ef24f59.png)

**Comment by elatif2020** [comment] 2023-09-20 07:52
We had a more general issue with the auth on DEV. Daniel is taking care of it

**Comment by NoamQA** [comment] 2023-09-27 06:39
@danielr18 
it looks fine in web stage and prod
but not in dev env.
can you check?


![Image](https://github.com/daostack/common-web/assets/129174316/e1ac9696-118d-4fcf-b40b-d92a425e60ab)

**Comment by elatif2020** [comment] 2023-10-04 10:26
@andreymikhadyuk can you please check whether it is BE or FE issue?

**Comment by andreymikhadyuk** [comment] 2023-10-04 11:52
@elatif2020 This is what we have for your example in the DB:
<img width="555" alt="image" src="https://github.com/daostack/common-web/assets/29727923/9002ae91-f880-449f-bf91-535e27c3737d">

**Comment by NoamQA** [comment] 2023-10-19 09:53
@elatif2020 @danielr18 
some of the issues fixed 
but not all

- [x]  when i update a space with another user - the time of the update doesnt change in the space channel of the common

- [ ]  in proposal and discussions the number of changes  doesnt work 


![Image](https://github.com/daostack/common-backend/assets/129174316/12501021-42fc-40dc-80c6-ee82c3bb0c7f)

**Comment by elatif2020** [comment] 2023-11-05 14:36
I think the issue is this https://github.com/daostack/common-backend/issues/2214
closing current ticket let's continue with the other ticket.

**Closed as completed** 2023-11-05 14:37 UTC
Labels: bug, Priority - A, V [production], blocked
